import type { Metadata } from "next";
import { prompt, sarabun } from "./ui/font";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${prompt.variable} h-full antialiased`}> 
    {/* เปลี่ยนตัวแปรตรงนี้ได้เลย */}
      <body className={`${prompt.className} min-h-full flex flex-col`}>
        {/* สลับเป็น prompt: เปลี่ยน sarabun → prompt ข้างบน */}
        {children}
      </body>
    </html>
  );
}
