import type { Metadata } from "next";
import { prompt, sarabun } from "./ui/font";
import "./globals.css";
import Navbar from "./_components/Navbar"; // import component (ไม่ใช่แค่ไฟล์)

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${prompt.variable} h-full antialiased`}> 
    {/* เปลี่ยนตัวแปรตรงนี้ได้เลย */}
      <body className={`${prompt.className} min-h-full flex flex-col`}>
        {/* Navbar อยู่ใน layout = แสดงทุกหน้า */}
        <Navbar />
        {/* children = หน้าที่เปลี่ยนไปตาม route */}
        {children}
      </body>
    </html>
  );
}
